baseurl = "https://www.jug-in.bayern"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "JUG Ingolstadt"
canonifyurls  = true

DefaultContentLanguage = "de"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "UA-158889963-1"

[Params]
  navbarTitle = "Java User Group Ingolstadt e.V."
  subtitle = "Java User Group Ingolstadt e.V."
  logo = "img/jug-in.png"
  favicon = "img/favicon.ico"
  dateFormat = "02.01.2006"
  commit = false
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[[Params.bigimg]]
  src = "img/coffee.jpg"

[Author]
  name = "jug in - Java User Group Ingolstadt e.V."
  email = "info@jug-in.bayern"
  twitter = "jug_ingolstadt"
  meetup = "jug-in"
  gitlab = "jug-in"
  github = "jug-in"
  linkedin = "8766833"
  xing = "java-user-group-ingolstadt-ev-c8ae-1109997"
  slack = "C01AM08L52P"
  ical = "https://calendar.google.com/calendar/embed?src=jug-in.bayern_7f1j2bk8rq8q0bttpfvvm9d2p8%40group.calendar.google.com&ctz=Europe%2FBerlin"

[[menu.main]]
    name = "Java-Treff"
    url = "page/java-treff/"
    weight = 2

[[menu.main]]
    name = "Publikationen"
    url = "page/publications/"
    weight = 3

[[menu.main]]
    name = "Verein"
    identifier = "verein"
    weight = 5

[[menu.main]]
    parent = "verein"
    name = "Mitglied werden"
    url = "https://www.vereinonline.org/jug_ingolstadt/?mitgliedsantrag"
    weight = 1

[[menu.main]]
    parent = "verein"
    name = "Portal"
    url = "https://www.vereinonline.org/jug_ingolstadt/"
    weight = 2

[[menu.main]]
    name = "Talks"
    identifier = "talks"
    weight = 4

[[menu.main]]
    parent = "talks"
    name = "ÜBERSICHT"
    url = "post"
    weight = 1

[[menu.main]]
    parent = "talks"
    name = "Elasticsearch"
    url = "post/2020-04-elasticsearch"
    weight = 2

[[menu.main]]
    parent = "talks"
    name = "Microstream"
    url = "post/2020-03-microstream"
    weight = 3

[[menu.main]]
    parent = "talks"
    name = "How to quit Vim"
    url = "post/2019-05-how-to-quit-vim"
    weight = 4


[[menu.main]]
    parent = "talks"
    name = "Cloud-Native Architektur"
    url = "post/2020-05-cloud-native-architecture"
    weight = 5

[[menu.main]]
    parent = "talks"
    name = "Going mouseless"
    url = "post/2020-07-mouseless"
    weight = 5
