baseurl = "https://preview.jug-in.bayern"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "JUG Ingolstadt"
canonifyurls  = true

DefaultContentLanguage = "de"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  navbarTitle = "Java-User-Group Ingolstadt e.V."
  subtitle = "Java-User-Group Ingolstadt e.V."
  logo = "img/jug-in.png"
  favicon = "img/favicon.ico"
  dateFormat = "02.01.2006"
  commit = false
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
[[Params.bigimg]]
  src = "img/cloud.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "jug in - Java-User-Group Ingolstadt e.V."
  email = "info@jug-in.bayern"
  gitlab = "jug-in"
  github = "jug-in"
  linkedin = "8766833"
  xing = "java-user-group-ingolstadt-ev-c8ae-1109997"
  discord = "GMBW4Gy"
  ical = "https://www.vereinonline.org/jug_ingolstadt/?ical"

[[menu.main]]
    name = "Verein"
    url = ""
    weight = 1

[[menu.main]]
    name = "Java-Treff"
    url = "page/java-treff/"
    weight = 2

[[menu.main]]
    name = "Impressum"
    url = "page/impressum/"
    weight = 4

[[menu.main]]
    name = "Talks"
    identifier = "talks"
    weight = 3

[[menu.main]]
    parent = "talks"
    name = "Apache Beam"
    url = "post/2020-02-apache-beam"
    weight = 1

[[menu.main]]
    parent = "talks"
    name = "Open Source APM Tools"
    url = "post/2019-08-open-source-apm-tools"
    weight = 1

[[menu.main]]
    parent = "talks"
    name = "Java module"
    url = "post/2019-07-java-module"
    weight = 1

[[menu.main]]
    parent = "talks"
    name = "Kotlin is more than an island"
    url = "post/2019-06-kotlin-more-than-an-island"
    weight = 1

[[menu.main]]
    parent = "talks"
    name = "Pattern Discussion"
    url = "post/2019-06-pattern-discussion"
    weight = 1

[[menu.main]]
    parent = "talks"
    name = "Coding Dojo"
    url = "post/2019-05-coding-dojo"
    weight = 1

[[menu.main]]
    parent = "talks"
    name = "Effective Java"
    url = "post/2019-05-effective-java"
    weight = 1

[[menu.main]]
    parent = "talks"
    name = "How to quit Vim"
    url = "post/2019-05-how-to-quit-vim"
    weight = 1

[[menu.main]]
    parent = "talks"
    name = "Java 12"
    url = "post/2019-04-java-12"
    weight = 1

[[menu.main]]
    parent = "talks"
    name = "Jmh Benchmark"
    url = "post/2019-04-jmh-benchmark"
    weight = 1

