name: Publish

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@main
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Site
        run: hugo --gc --minify --cleanDestinationDir

      - name: Publish Site
        uses: peaceiris/actions-gh-pages@main
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

